// ============================================
// Evarick Bot - Proprietary Software
// Copyright (c) 2026 Evarick. All Rights Reserved.
// Unauthorized copying or distribution is strictly prohibited.
// See LICENSE file for full terms.
// ============================================

/**
 * Extra recipes: gathering materials, herbs, fish → craft;
 * armor head/chest/legs + shields merged from armorShieldRecipes.js.
 */
import { armorShieldRecipes } from "./armorShieldRecipes.js";

export const gatheringRecipes = {
  "gather_oak_wood_plank_recipe": { "id": "gather_oak_wood_plank_recipe", "name": "Saw Plank (oak wood)", "category": "material", "result": { "itemId": "oak_plank", "quantity": 1 }, "materials": [{ "itemId": "oak_wood", "quantity": 12 }], "discoveryMaterials": ["oak_wood"], "description": "Saw oak_wood into planks" },
  "gather_pine_wood_plank_recipe": { "id": "gather_pine_wood_plank_recipe", "name": "Saw Plank (pine wood)", "category": "material", "result": { "itemId": "oak_plank", "quantity": 1 }, "materials": [{ "itemId": "pine_wood", "quantity": 12 }], "discoveryMaterials": ["pine_wood"], "description": "Saw pine_wood into planks" },
  "gather_birch_wood_plank_recipe": { "id": "gather_birch_wood_plank_recipe", "name": "Saw Plank (birch wood)", "category": "material", "result": { "itemId": "oak_plank", "quantity": 1 }, "materials": [{ "itemId": "birch_wood", "quantity": 10 }], "discoveryMaterials": ["birch_wood"], "description": "Saw birch_wood into planks" },
  "gather_mahogany_plank_recipe": { "id": "gather_mahogany_plank_recipe", "name": "Saw Plank (mahogany)", "category": "material", "result": { "itemId": "oak_plank", "quantity": 1 }, "materials": [{ "itemId": "mahogany", "quantity": 10 }], "discoveryMaterials": ["mahogany"], "description": "Saw mahogany into planks" },
  "gather_ebony_wood_plank_recipe": { "id": "gather_ebony_wood_plank_recipe", "name": "Saw Plank (ebony wood)", "category": "material", "result": { "itemId": "oak_plank", "quantity": 2 }, "materials": [{ "itemId": "ebony_wood", "quantity": 8 }], "discoveryMaterials": ["ebony_wood"], "description": "Saw ebony_wood into planks" },
  "gather_ironwood_plank_recipe": { "id": "gather_ironwood_plank_recipe", "name": "Saw Plank (ironwood)", "category": "material", "result": { "itemId": "oak_plank", "quantity": 2 }, "materials": [{ "itemId": "ironwood", "quantity": 8 }], "discoveryMaterials": ["ironwood"], "description": "Saw ironwood into planks" },
  "gather_dragonwood_plank_recipe": { "id": "gather_dragonwood_plank_recipe", "name": "Saw Plank (dragonwood)", "category": "material", "result": { "itemId": "oak_plank", "quantity": 3 }, "materials": [{ "itemId": "dragonwood", "quantity": 6 }], "discoveryMaterials": ["dragonwood"], "description": "Saw dragonwood into planks" },
  "gather_ghostwood_plank_recipe": { "id": "gather_ghostwood_plank_recipe", "name": "Saw Plank (ghostwood)", "category": "material", "result": { "itemId": "oak_plank", "quantity": 3 }, "materials": [{ "itemId": "ghostwood", "quantity": 6 }], "discoveryMaterials": ["ghostwood"], "description": "Saw ghostwood into planks" },
  "gather_world_tree_branch_plank_recipe": { "id": "gather_world_tree_branch_plank_recipe", "name": "Saw Plank (world tree branch)", "category": "material", "result": { "itemId": "oak_plank", "quantity": 4 }, "materials": [{ "itemId": "world_tree_branch", "quantity": 5 }], "discoveryMaterials": ["world_tree_branch"], "description": "Saw world tree branch into planks" },
  "gather_eternal_oak_plank_recipe": { "id": "gather_eternal_oak_plank_recipe", "name": "Saw Plank (eternal oak)", "category": "material", "result": { "itemId": "oak_plank", "quantity": 5 }, "materials": [{ "itemId": "eternal_oak", "quantity": 4 }], "discoveryMaterials": ["eternal_oak"], "description": "Saw eternal_oak into planks" },

  "gather_dirt_clump_recycle_recipe": { "id": "gather_dirt_clump_recycle_recipe", "name": "Dirt to Cloth", "category": "material", "result": { "itemId": "cloth", "quantity": 2 }, "materials": [{ "itemId": "dirt_clump", "quantity": 30 }], "discoveryMaterials": ["dirt_clump"], "description": "Press dirt into rough cloth" },
  "gather_broken_stone_recycle_recipe": { "id": "gather_broken_stone_recycle_recipe", "name": "Stone Scraps to Cloth", "category": "material", "result": { "itemId": "cloth", "quantity": 1 }, "materials": [{ "itemId": "broken_stone", "quantity": 14 }, { "itemId": "spider_silk", "quantity": 1 }], "discoveryMaterials": ["broken_stone"], "description": "Salvage stone scraps" },
  "gather_coal_iron_smelt_recipe": { "id": "gather_coal_iron_smelt_recipe", "name": "Smelt Iron (Coal)", "category": "material", "result": { "itemId": "iron_bar", "quantity": 1 }, "materials": [{ "itemId": "coal", "quantity": 4 }, { "itemId": "iron_ore", "quantity": 2 }], "discoveryMaterials": ["coal"], "description": "Smelt iron with coal" },
  "gather_stone_iron_recipe": { "id": "gather_stone_iron_recipe", "name": "Crush Stone to Iron", "category": "material", "result": { "itemId": "iron_bar", "quantity": 1 }, "materials": [{ "itemId": "stone", "quantity": 16 }], "discoveryMaterials": ["stone"], "description": "Refine crushed stone" },
  "gather_iron_ore_bar_recipe": { "id": "gather_iron_ore_bar_recipe", "name": "Smelt Iron Ore", "category": "material", "result": { "itemId": "iron_bar", "quantity": 1 }, "materials": [{ "itemId": "iron_ore", "quantity": 4 }], "discoveryMaterials": ["iron_ore"], "description": "Smelt raw iron ore" },
  "gather_copper_ore_bar_recipe": { "id": "gather_copper_ore_bar_recipe", "name": "Smelt Copper Ore", "category": "material", "result": { "itemId": "iron_bar", "quantity": 1 }, "materials": [{ "itemId": "copper_ore", "quantity": 5 }], "discoveryMaterials": ["copper_ore"], "description": "Refine copper ore" },
  "gather_silver_ore_bar_recipe": { "id": "gather_silver_ore_bar_recipe", "name": "Refine Silver Ore", "category": "material", "result": { "itemId": "iron_bar", "quantity": 2 }, "materials": [{ "itemId": "silver_ore", "quantity": 3 }], "discoveryMaterials": ["silver_ore"], "description": "Refine silver ore" },
  "gather_gold_ore_bar_recipe": { "id": "gather_gold_ore_bar_recipe", "name": "Smelt Gold Ore", "category": "material", "result": { "itemId": "gold_bar", "quantity": 1 }, "materials": [{ "itemId": "gold_ore", "quantity": 3 }], "discoveryMaterials": ["gold_ore"], "description": "Smelt gold ore" },
  "gather_mithril_ore_bar_recipe": { "id": "gather_mithril_ore_bar_recipe", "name": "Refine Mithril Ore", "category": "material", "result": { "itemId": "gold_bar", "quantity": 1 }, "materials": [{ "itemId": "mithril_ore", "quantity": 2 }, { "itemId": "iron_bar", "quantity": 2 }], "discoveryMaterials": ["mithril_ore"], "description": "Refine mithril" },
  "gather_obsidian_bar_recipe": { "id": "gather_obsidian_bar_recipe", "name": "Shape Obsidian", "category": "material", "result": { "itemId": "iron_bar", "quantity": 3 }, "materials": [{ "itemId": "obsidian", "quantity": 2 }], "discoveryMaterials": ["obsidian"], "description": "Work obsidian into bars" },
  "gather_dragon_stone_bar_recipe": { "id": "gather_dragon_stone_bar_recipe", "name": "Infuse Dragon Stone", "category": "material", "result": { "itemId": "gold_bar", "quantity": 2 }, "materials": [{ "itemId": "dragon_stone", "quantity": 2 }, { "itemId": "iron_bar", "quantity": 1 }], "discoveryMaterials": ["dragon_stone"], "description": "Channel dragon stone" },
  "gather_void_crystal_bar_recipe": { "id": "gather_void_crystal_bar_recipe", "name": "Channel Void Crystal", "category": "material", "result": { "itemId": "gold_bar", "quantity": 2 }, "materials": [{ "itemId": "void_crystal", "quantity": 1 }, { "itemId": "spirit_essence", "quantity": 2 }], "discoveryMaterials": ["void_crystal"], "description": "Stabilize void crystal" },

  "fish_old_boot_recycle_recipe": { "id": "fish_old_boot_recycle_recipe", "name": "Salvage Old Boots", "category": "material", "result": { "itemId": "cloth", "quantity": 2 }, "materials": [{ "itemId": "old_boot", "quantity": 8 }, { "itemId": "cloth", "quantity": 1 }], "discoveryMaterials": ["old_boot"], "description": "Salvage old boots" },
  "fish_torn_net_recipe": { "id": "fish_torn_net_recipe", "name": "Repair Torn Net", "category": "material", "result": { "itemId": "cloth", "quantity": 2 }, "materials": [{ "itemId": "torn_net", "quantity": 5 }, { "itemId": "spider_silk", "quantity": 1 }], "discoveryMaterials": ["torn_net"], "description": "Scrap nets into cloth" },
  "fish_soggy_scroll_recipe": { "id": "fish_soggy_scroll_recipe", "name": "Dry Soggy Scroll", "category": "consumable", "result": { "itemId": "wildberry_jam", "quantity": 1 }, "materials": [{ "itemId": "soggy_scroll", "quantity": 2 }, { "itemId": "wild_herb", "quantity": 3 }, { "itemId": "honey", "quantity": 1 }], "discoveryMaterials": ["soggy_scroll"], "description": "Recover usable pulp" },
  "fish_small_carp_jerky_recipe": { "id": "fish_small_carp_jerky_recipe", "name": "Carp Jerky", "category": "consumable", "result": { "itemId": "hunters_jerky", "quantity": 3 }, "materials": [{ "itemId": "small_carp", "quantity": 3 }, { "itemId": "honey", "quantity": 1 }], "discoveryMaterials": ["small_carp"], "description": "Smoke small carp" },
  "fish_river_trout_jerky_recipe": { "id": "fish_river_trout_jerky_recipe", "name": "Trout Jerky", "category": "consumable", "result": { "itemId": "hunters_jerky", "quantity": 4 }, "materials": [{ "itemId": "river_trout", "quantity": 2 }, { "itemId": "honey", "quantity": 1 }], "discoveryMaterials": ["river_trout"], "description": "Smoke river trout" },
  "fish_mudfish_broth_recipe": { "id": "fish_mudfish_broth_recipe", "name": "Mudfish Broth", "category": "consumable", "result": { "itemId": "minor_vitals_potion", "quantity": 1 }, "materials": [{ "itemId": "mudfish", "quantity": 3 }, { "itemId": "honey", "quantity": 1 }], "discoveryMaterials": ["mudfish"], "description": "Boil mudfish broth" },
  "fish_silver_bass_meal_recipe": { "id": "fish_silver_bass_meal_recipe", "name": "Bass Meal", "category": "consumable", "result": { "itemId": "minor_vitals_potion", "quantity": 2 }, "materials": [{ "itemId": "silver_bass", "quantity": 2 }, { "itemId": "pine_nut", "quantity": 2 }], "discoveryMaterials": ["silver_bass"], "description": "Cook silver bass" },
  "fish_swamp_eel_mana_recipe": { "id": "fish_swamp_eel_mana_recipe", "name": "Eel Mana Broth", "category": "consumable", "result": { "itemId": "great_mana_draught", "quantity": 1 }, "materials": [{ "itemId": "swamp_eel", "quantity": 2 }, { "itemId": "spirit_essence", "quantity": 1 }], "discoveryMaterials": ["swamp_eel"], "description": "Distill swamp eel" },
  "fish_spotted_pike_tonic_recipe": { "id": "fish_spotted_pike_tonic_recipe", "name": "Pike Tonic", "category": "consumable", "result": { "itemId": "mana_shard_tonic", "quantity": 2 }, "materials": [{ "itemId": "spotted_pike", "quantity": 2 }, { "itemId": "water_crystal", "quantity": 1 }], "discoveryMaterials": ["spotted_pike"], "description": "Render pike oil tonic" },
  "fish_golden_carp_mega_recipe": { "id": "fish_golden_carp_mega_recipe", "name": "Golden Carp Elixir", "category": "consumable", "result": { "itemId": "mega_potion", "quantity": 1 }, "materials": [{ "itemId": "golden_carp", "quantity": 1 }, { "itemId": "honey", "quantity": 3 }], "discoveryMaterials": ["golden_carp"], "description": "Brew golden carp elixir" },
  "fish_shadow_eel_recipe": { "id": "fish_shadow_eel_recipe", "name": "Shadow Eel Essence", "category": "material", "result": { "itemId": "spirit_essence", "quantity": 2 }, "materials": [{ "itemId": "shadow_eel", "quantity": 2 }, { "itemId": "shadow_essence", "quantity": 1 }], "discoveryMaterials": ["shadow_eel"], "description": "Extract shadow essence" },
  "fish_crystal_trout_tonic_recipe": { "id": "fish_crystal_trout_tonic_recipe", "name": "Crystal Trout Tonic", "category": "consumable", "result": { "itemId": "mana_shard_tonic", "quantity": 3 }, "materials": [{ "itemId": "crystal_trout", "quantity": 2 }, { "itemId": "water_essence", "quantity": 1 }], "discoveryMaterials": ["crystal_trout"], "description": "Crystal trout distillation" },
  "fish_ancient_catfish_feast_recipe": { "id": "fish_ancient_catfish_feast_recipe", "name": "Catfish Feast", "category": "consumable", "result": { "itemId": "great_mana_draught", "quantity": 2 }, "materials": [{ "itemId": "ancient_catfish", "quantity": 1 }, { "itemId": "honey", "quantity": 2 }, { "itemId": "deer_meat", "quantity": 1 }], "discoveryMaterials": ["ancient_catfish"], "description": "Cook ancient catfish feast" },
  "fish_void_fish_draught_recipe": { "id": "fish_void_fish_draught_recipe", "name": "Void Fish Draught", "category": "consumable", "result": { "itemId": "great_mana_draught", "quantity": 2 }, "materials": [{ "itemId": "void_fish", "quantity": 1 }, { "itemId": "night_essence", "quantity": 1 }], "discoveryMaterials": ["void_fish"], "description": "Stabilize void fish" },
  "fish_dragon_koi_gold_recipe": { "id": "fish_dragon_koi_gold_recipe", "name": "Dragon Koi Offering", "category": "material", "result": { "itemId": "gold_bar", "quantity": 2 }, "materials": [{ "itemId": "dragon_koi", "quantity": 1 }, { "itemId": "dragon_stone", "quantity": 1 }], "discoveryMaterials": ["dragon_koi"], "description": "Offer dragon koi" },
  "fish_phantom_eel_recipe": { "id": "fish_phantom_eel_recipe", "name": "Phantom Eel Phial", "category": "consumable", "result": { "itemId": "sting_balm", "quantity": 2 }, "materials": [{ "itemId": "phantom_eel", "quantity": 1 }, { "itemId": "ectoplasm", "quantity": 2 }], "discoveryMaterials": ["phantom_eel"], "description": "Bottle phantom eel oil" },

  "herb_wild_herb_jam_recipe": { "id": "herb_wild_herb_jam_recipe", "name": "Wild Herb Jam", "category": "consumable", "result": { "itemId": "wildberry_jam", "quantity": 2 }, "materials": [{ "itemId": "wild_herb", "quantity": 5 }, { "itemId": "honey", "quantity": 1 }], "discoveryMaterials": ["wild_herb"], "description": "Cook wild herbs" },
  "herb_wild_mushroom_jam_recipe": { "id": "herb_wild_mushroom_jam_recipe", "name": "Mushroom Preserve", "category": "consumable", "result": { "itemId": "wildberry_jam", "quantity": 2 }, "materials": [{ "itemId": "wild_mushroom", "quantity": 4 }, { "itemId": "wheat_grain", "quantity": 3 }], "discoveryMaterials": ["wild_mushroom"], "description": "Preserve mushrooms" },
  "herb_healing_herb_vitals_recipe": { "id": "herb_healing_herb_vitals_recipe", "name": "Healing Herb Vitals", "category": "consumable", "result": { "itemId": "minor_vitals_potion", "quantity": 2 }, "materials": [{ "itemId": "healing_herb", "quantity": 3 }, { "itemId": "honey", "quantity": 2 }], "discoveryMaterials": ["healing_herb"], "description": "Brew healing herb tonic" },
  "herb_poison_mushroom_cracker_recipe": { "id": "herb_poison_mushroom_cracker_recipe", "name": "Poison Mushroom Crackers", "category": "consumable", "result": { "itemId": "cobra_cracker", "quantity": 2 }, "materials": [{ "itemId": "poison_mushroom", "quantity": 3 }, { "itemId": "spider_venom", "quantity": 1 }], "discoveryMaterials": ["poison_mushroom"], "description": "Coat crackers in toxin" },
  "herb_swamp_root_balm_recipe": { "id": "herb_swamp_root_balm_recipe", "name": "Swamp Root Balm", "category": "consumable", "result": { "itemId": "sting_balm", "quantity": 2 }, "materials": [{ "itemId": "swamp_root", "quantity": 2 }, { "itemId": "honey", "quantity": 2 }], "discoveryMaterials": ["swamp_root"], "description": "Mix swamp balm" },
  "herb_moonflower_mana_recipe": { "id": "herb_moonflower_mana_recipe", "name": "Moonflower Draught", "category": "consumable", "result": { "itemId": "mana_shard_tonic", "quantity": 3 }, "materials": [{ "itemId": "moonflower", "quantity": 1 }, { "itemId": "spirit_essence", "quantity": 1 }], "discoveryMaterials": ["moonflower"], "description": "Distill moonflower" },
  "herb_dragon_herb_ember_recipe": { "id": "herb_dragon_herb_ember_recipe", "name": "Dragon Herb Ember", "category": "consumable", "result": { "itemId": "ember_jar", "quantity": 2 }, "materials": [{ "itemId": "dragon_herb", "quantity": 2 }, { "itemId": "fire_gland", "quantity": 1 }], "discoveryMaterials": ["dragon_herb"], "description": "Infuse ember jars" },
  "herb_phoenix_petal_health_recipe": { "id": "herb_phoenix_petal_health_recipe", "name": "Phoenix Petal Health", "category": "consumable", "result": { "itemId": "health_potion", "quantity": 4 }, "materials": [{ "itemId": "phoenix_petal", "quantity": 1 }, { "itemId": "honey", "quantity": 2 }], "discoveryMaterials": ["phoenix_petal"], "description": "Brew phoenix tincture" },
  "herb_shadow_root_mist_recipe": { "id": "herb_shadow_root_mist_recipe", "name": "Shadow Root Mist", "category": "consumable", "result": { "itemId": "mist_charm", "quantity": 2 }, "materials": [{ "itemId": "shadow_root", "quantity": 2 }, { "itemId": "bat_wing", "quantity": 2 }], "discoveryMaterials": ["shadow_root"], "description": "Bind shadow mist charm" },
  "herb_elixir_flower_mana_recipe": { "id": "herb_elixir_flower_mana_recipe", "name": "Elixir Flower Draught", "category": "consumable", "result": { "itemId": "great_mana_draught", "quantity": 2 }, "materials": [{ "itemId": "elixir_flower", "quantity": 1 }, { "itemId": "spirit_essence", "quantity": 2 }], "discoveryMaterials": ["elixir_flower"], "description": "Brew elixir flower draught" },
  "herb_soul_herb_mega_recipe": { "id": "herb_soul_herb_mega_recipe", "name": "Soul Herb Tincture", "category": "consumable", "result": { "itemId": "mega_potion", "quantity": 1 }, "materials": [{ "itemId": "soul_herb", "quantity": 1 }, { "itemId": "honey", "quantity": 5 }, { "itemId": "pixie_dust", "quantity": 1 }], "discoveryMaterials": ["soul_herb"], "description": "Brew soul herb tincture" },
  "herb_field_antidote_recipe": { "id": "herb_field_antidote_recipe", "name": "Field Antidote", "category": "consumable", "result": { "itemId": "antidote", "quantity": 3 }, "materials": [{ "itemId": "healing_herb", "quantity": 2 }, { "itemId": "poison_mushroom", "quantity": 2 }, { "itemId": "wild_herb", "quantity": 3 }], "discoveryMaterials": ["poison_mushroom"], "description": "Mix a crude antidote from herbs" },

  ...armorShieldRecipes,
};
